apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
spec:
  replicas: 2
  selector:
    matchLabels:
      name: otelcol
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        name: otelcol
    spec:
      containers:
      - name: otelcol
        image: annanay25/otelcol-tail-sampling:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: oc-receiver
          containerPort: 55678
        - name: jaeger-receiver
          containerPort: 6831
        - name: metrics
          containerPort: 8888
